mixed-port: 7999
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: rule
log-level: debug
external-controller: :9090
profile:
  store-selected: true
  store-fake-ip: true
ipv6: true
find-process-mode: strict
global-client-fingerprint: chrome
tcp-concurrent: true

sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
    - www.google.com
    - google.com
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.apple.com
dns:
  cache-algorithm: arc
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  fake-ip-range: 198.18.0.1/16
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*'
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time-ios.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.qq.com'
    - '+.tencent.com'
    - '+.srv.nintendo.net'
    - '*.n.n.srv.nintendo.net'
    - '+.cdn.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - 'na.b.g-tun.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.ff14.sdo.com'
    - 'ff.dorado.sdo.com'
    - '*.mcdn.bilivideo.cn'
    - '+.media.dssott.com'
    - 'shark007.net'
    - 'Mijia Cloud'
    - '+.cmbchina.com'
    - '+.cmbimg.com'
    - 'adguardteam.github.io'
    - 'adrules.top'
    - 'anti-ad.net'
    - 'local.adguard.org'
    - 'static.adtidy.org'
    - '+.sandai.net'
    - '+.n0808.com'
    - '+.3gppnetwork.org'
    - '+.uu.163.com'
    - 'ps.res.netease.com'
    - 1337.abcvg.info
    - aboutbeautifulgallopinghorsesinthegreenpasture.online
    - bt.okmp3.ru
    - bvarf.tracker.sh
    - ch3oh.ru
    - ipv6.rer.lol
    - nyaa.tracker.wf
    - open.acgnxtracker.com
    - p2p.0g.cx
    - retracker.hotplug.ru
    - t.acg.rip
    - tk.greedland.net
    - torrentsmd.com
    - tracker.bt4g.com
    - tracker.edkj.club
    - tracker.electro-torrent.pl
    - tracker.files.fm
    - tracker.gbitt.info
    - tracker.ipv6tracker.org
    - tracker.ipv6tracker.ru
    - tracker.k.vu
    - tracker.opentrackr.org
    - tracker.qu.ax
    - tracker.renfei.net
    - tracker2.itzmx.com
    - tracker3.itzmx.com
    - tracker4.itzmx.com
    - wepzone.net
    - www.all4nothin.net
    - www.peckservers.com
    - www.wareztorrent.com
    - 1337.abcvg.info
    - shahidrazi.online
    - t1.hloli.org
    - tr.abir.ga
    - tr.qfruiti.com
    - tracker.cloudit.top
    - tracker.ipfsscan.io
    - tracker.kuroy.me
    - tracker.lilithraws.org
    - tracker.loligirl.cn
    - tracker.renfei.net
    - tracker.tamersunion.org
    - tracker1.520.jp
    - trackers.mlsub.net
    - trackers.ptlsp.com
    - www.peckservers.com
    - yolo.liberbear.com
    - 1c.premierzal.ru
    - aarsen.me
    - aegir.sexy
    - amigacity.xyz
    - black-bird.ynh.fr
    - bt.ktrackers.com
    - bt1.archive.org
    - bt2.archive.org
    - bubu.mapfactor.com
    - concen.org
    - d40969.acod.regrucolo.ru
    - ec2-18-191-163-220.us-east-2.compute.amazonaws.com
    - epider.me
    - evan.im
    - exodus.desync.com
    - fh2.cmp-gaming.com
    - free.publictracker.xyz
    - ipv4.rer.lol
    - ipv6.fuuuuuck.com
    - jutone.com
    - martin-gebhardt.eu
    - moonburrow.club
    - movies.zsw.ca
    - new-line.net
    - ns1.monolithindustries.com
    - odd-hd.fr
    - oh.fuuuuuck.com
    - open.demonii.com
    - open.demonoid.ch
    - open.free-tracker.ga
    - open.publictracker.xyz
    - open.u-p.pw
    - open.xxtor.com
    - opentor.org
    - opentracker.io
    - p2p.publictracker.xyz
    - p4p.arenabg.com
    - public.demonoid.ch
    - public.publictracker.xyz
    - public.tracker.vraphim.com
    - retracker.hotplug.ru
    - retracker.lanta.me
    - retracker01-msk-virt.corbina.net
    - run-2.publictracker.xyz
    - run.publictracker.xyz
    - ryjer.com
    - seedpeer.net
    - su-data.com
    - tamas3.ynh.fr
    - tk1.trackerservers.com
    - torrents.artixlinux.org
    - tracker-udp.gbitt.info
    - tracker.0x7c0.com
    - tracker.anima.nz
    - tracker.ccp.ovh
    - tracker.cyberia.is
    - tracker.ddunlimited.net
    - tracker.dler.com
    - tracker.dler.org
    - tracker.dump.cl
    - tracker.edkj.club
    - tracker.farted.net
    - tracker.filemail.com
    - tracker.fnix.net
    - tracker.jamesthebard.net
    - tracker.moeking.me
    - tracker.opentrackr.org
    - tracker.picotorrent.one
    - tracker.publictracker.xyz
    - tracker.qu.ax
    - tracker.skyts.net
    - tracker.srv00.com
    - tracker.t-rb.org
    - tracker.theoks.net
    - tracker.therarbg.com
    - tracker.therarbg.to
    - tracker.tiny-vps.com
    - tracker.torrent.eu.org
    - tracker.torrust-demo.com
    - tracker.tryhackx.org
    - tracker.vds.nz
    - tracker1.bt.moack.co.kr
    - tracker1.myporn.club
    - tracker2.dler.com
    - tracker2.dler.org
    - tracker2.itzmx.com
    - tracker3.itzmx.com
    - tracker4.itzmx.com
    - wepzone.net
    - www.torrent.eu.org
  nameserver:
    - 'https://223.5.5.5/dns-query#h3=true'
    - https://1.12.12.12/dns-query