# 是否开启快速模式，快速模式下仅测试连通性
fast_mode = false

# 待测速的订阅节点
# 支持网络地址 https://xxx
# 支持本地地址（绝对地址）/User/xxx/xx.yml
# 支持单个订阅链接，ss://xxx
subs = [
]

# 生成订阅所使用的 subconverter 的配置地址，可使用网络地址
# 默认为 subconverter/config/release.toml
sub_config_url = "config/release.toml"
# 是否重命名节点，打开后会使用 geoip 等方式进行代理真实 IP 和地理地址查询
rename_node = true
rename_pattern = "${COUNTRYCODE}_${CITY}_${ISP}"

# 是否需要加上代理池的节点一起筛选
need_add_pool = false
# 代理节点池
pools = [
    "https://sub.tgzdyz2.xyz/sub",
    "https://raw.githubusercontent.com/yebekhe/TVC/main/subscriptions/meta/mix",
    "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml",
    "https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml",
    "https://raw.githubusercontent.com/Misaka-blog/chromego_merge/main/sub/base64.txt",
    "https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml",
    "https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml",
    "https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml",
]
# https://linux.do/t/topic/44934


# 连通性测试
[connect_test]
url = "http://www.gstatic.com/generate_204"
expected = 204
timeout = 1000

# 网站测试配置
[websites.google]
url = "http://www.google.com/generate_204"
expected = 204
timeout = 1000

[other]
sub_converter_port = 25501
clash_external_port = 9091