# 是否开启快速模式，快速模式下仅测试连通性
fast_mode = false

# 待测速的订阅节点
# 支持网络地址 https://xxx
# 支持本地地址（绝对地址）/User/xxx/xx.yml
# 支持单个订阅链接，ss://xxx
subs = [
"https://api.dingyueapi.win/api/v1/client/subscribe?token=7fff8a52b31e2f0f145717c73eb0191f",
"https://sub.xfltd.bond/api/v1/client/subscribe?token=c58e37b673582eefc393cd42dd19a0fb",
"https://www.super-plane.top/api/v1/client/subscribe?token=25e8255772f4adfb7545b01c1455cce7",
"http://202.91.33.173:50050/api/v1/client/subscribe?token=e4add8e263324544504f850b6608f153",
"https://dr1.opensub1.xyz/api/v1/client/subscribe?token=UDT1Hj9L1mg5Ob8vl82pZj9rMwl5lxdc",
]

# 是否重命名节点，打开后会使用 geoip 等方式进行代理真实 IP 和地理地址查询
rename_node = true
rename_pattern = "${COUNTRYCODE}_${CITY}_${ISP}"

# 是否需要加上代理池的节点一起筛选
need_add_pool = true
# 代理节点池
pools = [
    "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml"
]

# 测试分组大小
test_group_size = 50

# 连通性测试
[connect_test]
url = "http://www.google.com/generate_204"
expected = 204
timeout = 500

# 带宽测速配置
[speed_test]
enabled = false
url = "https://speed.cloudflare.com/__down?bytes=104857600"
timeout = 3000
