version = 1
[custom]
enable_rule_generator = false
exclude_remarks = ["(到期|剩余流量|时间|官网|产品|@vpnhat|@EXM3U)"]

[[custom_groups]]
name = "自动选择"
type = "url-test"
rule = [".*"]
url = "https://www.google.com/generate_204"
interval = 10
lazy = false