version = 1
[custom]
clash_rule_base = "base/clash_base.yaml"
add_emoji = true

[[custom_groups]]
name = "PROXY"
type = "select"
rule = ["[]LoadBalance", "[]Fallback", "[]Select", "[]HK", "[]TW", "[]JP", "[]SG", "[]US"]

[[custom_groups]]
name = "Select"
type = "select"
rule = [".*"]

#[[custom_groups]]
#name = "DL"
#type = "select"
#rule = ["(DL|下载|大流量|大数据)"]

[[custom_groups]]
name = "LoadBalance"
type = "load-balance"
rule = [".*"]
url = "http://www.google.com/generate_204"
interval = 600
timeout = 3
tolerance = 500

[[custom_groups]]
name = "Fallback"
type = "fallback"
rule = ["[]HK", "[]TW", "[]JP", "[]SG", "[]US"]
url = "http://www.google.com/generate_204"
interval = 600
timeout = 3
tolerance = 500

[[custom_groups]]
name = "HK"
type = "url-test"
rule = ["(HK|Hongkong|Hong Kong|HongKong|HONG KONG|香港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|穗港|京港)"]
url = "http://www.google.com/generate_204"
interval = 600
timeout = 3
tolerance = 500

[[custom_groups]]
name = "TW"
type = "url-test"
rule = ["(TW|Taiwan|TAIWAN|台湾|台北|台中|新北|彰化|CHT|台|HINET)"]
url = "http://www.google.com/generate_204"
interval = 600
timeout = 3
tolerance = 500


[[custom_groups]]
name = "JP"
type = "url-test"
rule = ["(JP|JP-|JP_|Japan|JAPAN|日本|东京|大阪|埼玉|穗日|川日|中日|泉日|杭日|深日|辽日|广日|Tokyo)"]
url = "http://www.google.com/generate_204"
interval = 600
timeout = 3
tolerance = 500

[[custom_groups]]
name = "SG"
type = "url-test"
rule = ["(SG|SG-|SG_|Singapore|SINGAPORE|新加坡|狮城|沪新|京新|泉新|穗新|深新|杭新|广新|廣新|滬新)"]
url = "http://www.google.com/generate_204"
interval = 600
timeout = 3
tolerance = 500

[[custom_groups]]
name = "US"
type = "url-test"
rule = ["(US|USA|America|United States|美国|美|京美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|矽谷|拉斯维加斯|洛杉矶|圣何塞|圣荷西|圣克拉拉|西雅图|芝加哥|沪美|哥伦布|纽约)"]
url = "http://www.google.com/generate_204"
interval = 600
timeout = 3
tolerance = 500